Repository HackYourCareer/SmartKickers, pull requests merged in 2022-07, with the labels that each got.

#59 Frontend/React code refactor after review
  frontend/smart-kickers-game/.prettierrc
  frontend/smart-kickers-game/README.md
  frontend/smart-kickers-game/__mocks__/ws.js
  frontend/smart-kickers-game/public/index.html
  frontend/smart-kickers-game/public/logo192.png
  frontend/smart-kickers-game/public/logo512.png
  frontend/smart-kickers-game/public/manifest.json
  frontend/smart-kickers-game/public/robots.txt
  frontend/smart-kickers-game/src/App.css
  frontend/smart-kickers-game/src/App.js
  frontend/smart-kickers-game/src/App.spec.js
  frontend/smart-kickers-game/src/components/Button.css
  frontend/smart-kickers-game/src/components/Button.js
  frontend/smart-kickers-game/src/components/button.css
  frontend/smart-kickers-game/src/components/button.js
  frontend/smart-kickers-game/src/index.css
  frontend/smart-kickers-game/src/logo.svg
  frontend/smart-kickers-game/src/tests/App.spec.js
  frontend/smart-kickers-game/src/tests/helpers.js
Labels: size/L

#63 refactor adapter
  internal/controller/server/adapter/dispatcher.go
Labels: size/S

#64 Add game structure
  go.mod
  go.sum
  internal/model/game.go
  internal/model/game_test.go
Labels: size/S

#68 move backend files to backend foler, remove unnecessary files, update…
  .DS_Store
  .gitignore
  .idea/.gitignore
  .idea/SmartKickers.iml
  .idea/modules.xml
  .idea/vcs.xml
  backend/go.mod
  backend/go.sum
  backend/internal/controller/server/adapter/dispatcher.go
  backend/internal/controller/server/handlers/connection.go
  backend/internal/controller/server/handlers/msg_handler.go
  backend/internal/controller/server/server.go
  backend/internal/model/game.go
  backend/internal/model/game_test.go
  backend/internal/service/game_manager.go
  backend/main.go
Labels: small refactor
