Repository HackYourCareer/SmartKickers, pull requests merged in 2022-09, with the labels that each got.

#143 Add manual goals manipulation history sendig
  backend/internal/model/game.go
Labels: size/M, Go

#145 Fix adding goals to goalsArray after game ended
  frontend/smart-kickers-game/src/App.js
Labels: size/S, React

#144 Add fastest shot of the game statistics
  frontend/smart-kickers-game/src/apis/getStatistics.js
  frontend/smart-kickers-game/src/components/Game/GameStatistics/GameStatistics.css
  frontend/smart-kickers-game/src/components/Game/GameStatistics/GameStatistics.js
Labels: size/M, React

#151 Hide everything when game start button isn't pressed
  frontend/smart-kickers-game/src/App.js
  frontend/smart-kickers-game/src/components/Button/Button.css
  frontend/smart-kickers-game/src/components/Game/CurrentGameplay/CurrentGameplay.js
  frontend/smart-kickers-game/src/components/Game/GameHistory/GameHistory.css
  frontend/smart-kickers-game/src/components/Game/GameResults/GameResults.js
  frontend/smart-kickers-game/src/tests/App.spec.js
Labels: size/M, React

#152 Add manually added/substracted goal stats in frontend
  frontend/smart-kickers-game/src/components/Game/GameStatistics/GameStatistics.js
Labels: size/S, React

#159 Continuous delivery
  .github/workflows/backend-cd.yml
  .github/workflows/frontend-cd.yml
Labels: size/M, DevOps

#160 Fix missing working directory
  .github/workflows/backend-cd.yml
  .github/workflows/frontend-cd.yml
Labels: size/XS, DevOps

#161 Fix wrong name of workflow
  .github/workflows/frontend-cd.yml
Labels: size/XS, DevOps

#116 Add configuration for golangci-lint
  backend/.golangci.yml
  backend/internal/controller/adapter/dispatcher.go
  backend/internal/controller/adapter/dispatcher_test.go
  backend/internal/controller/adapter/shot_message_test.go
  backend/internal/controller/server/msg_handler.go
  backend/internal/controller/server/msg_handler_test.go
  backend/internal/controller/server/server.go
  backend/internal/model/game.go
  backend/internal/model/game_test.go
Labels: size/M, DevOps

#154 Move heatmap to another struct
  backend/internal/controller/server/msg_handler.go
  backend/internal/controller/server/server.go
  backend/internal/model/game.go
  backend/internal/model/game_test.go
Labels: size/M, urgent, Sanity Check Required, Go

#169 Fix errors found by golangci-lint after new config
  backend/internal/controller/adapter/dispatcher.go
  backend/internal/controller/server/msg_handler.go
  backend/internal/model/game.go
  backend/internal/model/game_test.go
Labels: size/XS, Go

#117 Fix changes requested in Pr #91
  backend/internal/controller/adapter/dispatcher_test.go
  backend/internal/controller/adapter/shot_message.go
  backend/internal/controller/adapter/shot_message_test.go
  backend/internal/controller/server/msg_handler.go
  backend/internal/model/game_test.go
Labels: size/S, Go

#139 Add counting shots on goal for each team
  backend/internal/config/config.go
  backend/internal/controller/adapter/dispatcher.go
  backend/internal/controller/adapter/shot_message.go
  backend/internal/controller/adapter/shot_message_test.go
  backend/internal/model/game.go
  backend/internal/model/game_test.go
Labels: size/M, urgent, Go

#172 Update image name in k8s deployment definition for go
  backend/k8s-deployment.yml
Labels: size/XS, DevOps

#164 Move table items to components
  frontend/smart-kickers-game/src/App.js
  frontend/smart-kickers-game/src/components/Game/GameStatistics/GameStatistics.css
  frontend/smart-kickers-game/src/components/Game/GameStatistics/GameStatistics.js
  frontend/smart-kickers-game/src/components/Game/GameStatistics/StatisticsItems/FastestShot.js
  frontend/smart-kickers-game/src/components/Game/GameStatistics/StatisticsItems/FinalScores.js
  frontend/smart-kickers-game/src/components/Game/GameStatistics/StatisticsItems/ManualChangedGoals.js
  frontend/smart-kickers-game/src/components/Game/GameStatistics/StatisticsItems/StatisticItem.css
  frontend/smart-kickers-game/src/components/Game/GameStatistics/StatisticsItems/TeamIcons.js
Labels: size/M, React

#109 Add heatmap generation on frontend
  backend/internal/model/game.go
  frontend/smart-kickers-game/package-lock.json
  frontend/smart-kickers-game/package.json
  frontend/smart-kickers-game/src/App.js
  frontend/smart-kickers-game/src/assets/images/pitch.png
  frontend/smart-kickers-game/src/components/Game/GameStatistics/GameStatistics.js
  frontend/smart-kickers-game/src/components/Heatmap/Colors.js
  frontend/smart-kickers-game/src/components/Heatmap/Heatmap.css
  frontend/smart-kickers-game/src/components/Heatmap/Heatmap.js
  frontend/smart-kickers-game/src/hooks/useHeatmap.js
Labels: size/L, React

#178 Remove wsl from golangci-lint config
  backend/.golangci.yml
Labels: size/XS, DevOps

#94 Split handler functions into two files
  backend/internal/controller/adapter/shot_message.go
  backend/internal/controller/server/table_handler_test.go
  backend/internal/controller/server/table_handlers.go
  backend/internal/controller/server/view_handlers.go
  backend/internal/controller/server/view_handlers_test.go
Labels: size/L, Go

#166 Add number of shots statistics
  frontend/smart-kickers-game/src/components/Game/GameStatistics/GameStatistics.css
  frontend/smart-kickers-game/src/components/Game/GameStatistics/GameStatistics.js
  frontend/smart-kickers-game/src/components/Game/GameStatistics/NumberOfShots.js
Labels: size/S, React

#183 Fix bug when no stats accure
  frontend/smart-kickers-game/src/components/Game/GameStatistics/GameStatistics.js
Labels: size/XS, React

#184 Add browserRouter
  frontend/smart-kickers-game/package-lock.json
  frontend/smart-kickers-game/package.json
  frontend/smart-kickers-game/src/App.js
  frontend/smart-kickers-game/src/StartGame.css
  frontend/smart-kickers-game/src/StartGame.js
  frontend/smart-kickers-game/src/components/Button/NewGameButton.js
  frontend/smart-kickers-game/src/components/Game/CurrentGameplay/CurrentGameplay.js
  frontend/smart-kickers-game/src/components/Game/GameHistory/GameHistory.js
  frontend/smart-kickers-game/src/components/Game/GameResults/GameResults.js
  frontend/smart-kickers-game/src/components/Game/GameStatistics/GameStatistics.js
  frontend/smart-kickers-game/src/components/Game/GameStatistics/StatisticsItems/FinalScores.js
  frontend/smart-kickers-game/src/components/Game/GameStatistics/StatisticsItems/ManualChangedGoals.js
  frontend/smart-kickers-game/src/components/Game/Header/StatsHeader.css
  frontend/smart-kickers-game/src/components/Game/Header/StatsHeader.js
  frontend/smart-kickers-game/src/contexts/CurrentGameplayContext.js
  frontend/smart-kickers-game/src/contexts/GameDataContext.js
  frontend/smart-kickers-game/src/hooks/useCurrentGameplay.js
  frontend/smart-kickers-game/src/index.js
  frontend/smart-kickers-game/src/router/Router.js
  frontend/smart-kickers-game/src/router/StatsItem.js
  frontend/smart-kickers-game/src/tests/StartGame.spec.js
Labels: size/L, React

#163 Rebuild data storing structure
  backend/internal/controller/adapter/dispatcher.go
  backend/internal/controller/adapter/shot_message_test.go
  backend/internal/controller/server/view_handlers.go
  backend/internal/model/game.go
  backend/internal/model/game_test.go
Labels: size/L, Go

#187 Adjust frontend to new API
  frontend/smart-kickers-game/src/components/Game/GameStatistics/GameStatistics.js
  frontend/smart-kickers-game/src/components/Game/GameStatistics/NumberOfShots.js
  frontend/smart-kickers-game/src/components/Game/GameStatistics/StatisticsItems/FastestShot.js
  frontend/smart-kickers-game/src/components/Game/GameStatistics/StatisticsItems/ManualChangedGoals.js
  frontend/smart-kickers-game/src/components/Game/Header/StatsHeader.js
  frontend/smart-kickers-game/src/hooks/useHeatmap.js
Labels: size/S, React

#147 Readme adjustment
  README.md
  assets/reactApp.png
Labels: documentation, size/M

#179 Simplify launching readme
  README.md
Labels: documentation, size/XS

#182 Add documentation diagrams
  documentation/Component_Go.jpg
  documentation/Container.jpg
  documentation/Context.jpg
  documentation/SmartKickers_doc.pdf
Labels: documentation, size/XS

#188 Change color and shape of heatmap marks
  frontend/smart-kickers-game/src/components/Heatmap/Colors.js
  frontend/smart-kickers-game/src/components/Heatmap/Heatmap.css
Labels: size/M, React

#190 Fix game-history
  frontend/smart-kickers-game/src/hooks/useCurrentGameplay.js
Labels: size/XS, React

#189 Change heatmap incrementation
  backend/internal/model/game.go
  backend/internal/model/game_test.go
Labels: size/M, Sanity Check Required, Go

#191 Heatmap imporvement
  frontend/smart-kickers-game/src/components/Heatmap/Colors.js
  frontend/smart-kickers-game/src/components/Heatmap/Heatmap.css
  frontend/smart-kickers-game/src/components/Heatmap/Heatmap.js
Labels: size/M, React

#192 Fix game-history again
  frontend/smart-kickers-game/src/StartGame.js
  frontend/smart-kickers-game/src/contexts/CurrentGameplayContext.js
  frontend/smart-kickers-game/src/contexts/GameDataContext.js
  frontend/smart-kickers-game/src/hooks/useCurrentGameplay.js
Labels: size/M, React

#193 Make stats names more consistent
  frontend/smart-kickers-game/src/components/Game/GameStatistics/NumberOfShots.js
  frontend/smart-kickers-game/src/components/Game/GameStatistics/StatisticsItems/FastestShot.js
  frontend/smart-kickers-game/src/components/Game/GameStatistics/StatisticsItems/FinalScores.js
Labels: size/XS, React

#194 Optimize heatmap generating on frontend
  backend/internal/model/game.go
  backend/internal/model/game_test.go
  frontend/smart-kickers-game/src/components/Heatmap/Heatmap.js
  frontend/smart-kickers-game/src/hooks/useHeatmap.js
Labels: size/M, React, Go
