Repository HackYourCareer/SmartKickers, pull requests merged in 2022-08, with the labels that each got.

#66 Server restructurisation
  .DS_Store
  backend/go.mod
  backend/internal/controller/adapter/dispatcher.go
  backend/internal/controller/server/adapter/dispatcher.go
  backend/internal/controller/server/handlers/connection.go
  backend/internal/controller/server/handlers/msg_handler.go
  backend/internal/controller/server/msg_handler.go
  backend/internal/controller/server/server.go
  backend/internal/model/game.go
  backend/internal/model/game_test.go
  backend/internal/service/game_manager.go
  backend/main.go
Labels: size/L

#71 REST API for reset score functionality
  backend/go.mod
  backend/go.sum
  backend/internal/controller/server/msg_handler.go
  backend/internal/controller/server/server.go
Labels: size/XS

#72 Feature undo goal
  backend/internal/model/game.go
  backend/internal/model/game_test.go
Labels: size/M

#65 add buttons to manipulate score
  frontend/smart-kickers-game/package-lock.json
  frontend/smart-kickers-game/package.json
  frontend/smart-kickers-game/src/App.css
  frontend/smart-kickers-game/src/App.js
  frontend/smart-kickers-game/src/apis/goalManipulation.js
  frontend/smart-kickers-game/src/components/Button.css
  frontend/smart-kickers-game/src/components/GameResults.css
  frontend/smart-kickers-game/src/components/GameResults.js
  frontend/smart-kickers-game/src/config.js
  frontend/smart-kickers-game/src/constants/score.js
Labels: size/L

#67 Fix Reset Button - frontend
  frontend/smart-kickers-game/package-lock.json
  frontend/smart-kickers-game/package.json
  frontend/smart-kickers-game/src/App.js
  frontend/smart-kickers-game/src/apis/Game.js
  frontend/smart-kickers-game/src/apis/Game.spec.js
  frontend/smart-kickers-game/src/tests/App.spec.js
Labels: size/M

#75 HTTP API for score manipulation
  backend/internal/controller/server/msg_handler.go
  backend/internal/controller/server/server.go
  backend/internal/model/game.go
  backend/internal/model/game_test.go
Labels: size/M

#81 Handler for sending score
  backend/internal/controller/server/msg_handler.go
  backend/internal/controller/server/server.go
  backend/internal/model/game.go
  backend/internal/model/game_test.go
  frontend/smart-kickers-game/src/App.js
Labels: size/M, urgent

#86 Add Logrus
  backend/go.mod
  backend/go.sum
  backend/internal/controller/server/msg_handler.go
  backend/internal/controller/server/server.go
  backend/main.go
Labels: size/M

#95 Dockerizing go and frontend
  backend/Dockerfile
  docker-compose.yml
  frontend/smart-kickers-game/.dockerignore
  frontend/smart-kickers-game/Dockerfile
  frontend/smart-kickers-game/package-lock.json
Labels: size/M

#77 Add test for msg_handler.go
  backend/internal/controller/server/msg_handler_test.go
  backend/internal/controller/server/server.go
Labels: size/L, urgent

#89 Add OpenAPI documentation
  openapi/openapi.yaml
Labels: documentation, size/M

#90 Add a table with statistics
  frontend/smart-kickers-game/package-lock.json
  frontend/smart-kickers-game/package.json
  frontend/smart-kickers-game/src/App.css
  frontend/smart-kickers-game/src/App.js
  frontend/smart-kickers-game/src/apis/resetGame.js
  frontend/smart-kickers-game/src/apis/resetGame.spec.js
  frontend/smart-kickers-game/src/appConfig.js
  frontend/smart-kickers-game/src/components/Button.js
  frontend/smart-kickers-game/src/components/Button/Button.css
  frontend/smart-kickers-game/src/components/Button/Button.js
  frontend/smart-kickers-game/src/components/Game/CurrentGameplay/CurrentGameplay.css
  frontend/smart-kickers-game/src/components/Game/CurrentGameplay/CurrentGameplay.js
  frontend/smart-kickers-game/src/components/Game/GameResults/GameResults.css
  frontend/smart-kickers-game/src/components/Game/GameResults/GameResults.js
  frontend/smart-kickers-game/src/components/Game/GameStatistics/GameStatistics.css
  frontend/smart-kickers-game/src/components/Game/GameStatistics/GameStatistics.js
  frontend/smart-kickers-game/src/index.js
Labels: size/L

#104 Add CI to project
  .github/workflows/backend-ci.yml
  .github/workflows/frontend-ci.yml
Labels: size/M

#106 Fix missing error handling
  backend/internal/controller/server/msg_handler.go
Labels: size/S

#108 Fix tests in frontend
  frontend/smart-kickers-game/src/apis/goalManipulation.js
  frontend/smart-kickers-game/src/apis/resetGame.spec.js
  frontend/smart-kickers-game/src/tests/App.spec.js
Labels: size/XS

#107 Change colors according to SAP guidelines
  frontend/smart-kickers-game/src/App.css
  frontend/smart-kickers-game/src/components/Button/Button.css
  frontend/smart-kickers-game/src/components/Game/GameStatistics/GameStatistics.css
Labels: size/M, small refactor

#110 [Fix] points still counting after ending the game
  frontend/smart-kickers-game/src/App.js
  frontend/smart-kickers-game/src/components/Game/GameStatistics/GameStatistics.js
Labels: bug, size/XS

#102 Update readme.md
  README.md
  assets/appLaunch.png
  assets/goLaunch.png
  assets/reactApp.png
Labels: documentation, size/S

#91 Add fastest shot detecting
  backend/internal/config/config.go
  backend/internal/controller/adapter/dispatcher.go
  backend/internal/controller/adapter/dispatcher_test.go
  backend/internal/controller/adapter/shot_message.go
  backend/internal/controller/adapter/shot_message_test.go
  backend/internal/controller/server/msg_handler.go
  backend/internal/controller/server/server.go
  backend/internal/model/game.go
  backend/internal/model/game_test.go
  backend/main.go
Labels: size/L, urgent

#120 Kubernetes Go Deployment files
  backend/k8s-deployment.yml
Labels: size/M

#132 Change image source to temporary remote registry
  backend/k8s-deployment.yml
Labels: size/XS

#126 Add ball position reading
  backend/internal/controller/adapter/dispatcher.go
  backend/internal/controller/adapter/dispatcher_test.go
  backend/internal/controller/server/msg_handler.go
  backend/internal/controller/server/msg_handler_test.go
Labels: size/S, urgent

#112 Add tests for goalManipulation method
  frontend/smart-kickers-game/src/apis/goalManipulation.js
  frontend/smart-kickers-game/src/apis/updateScores.js
  frontend/smart-kickers-game/src/apis/updateScores.spec.js
  frontend/smart-kickers-game/src/components/Game/GameResults/GameResults.js
Labels: size/M

#100 Manually added and subtracted goals counter
  backend/internal/config/config.go
  backend/internal/controller/server/msg_handler.go
  backend/internal/model/game.go
  backend/internal/model/game_test.go
Labels: size/M

#129 Add heatmap generation on backend
  backend/internal/config/config.go
  backend/internal/model/game.go
  backend/internal/model/game_test.go
Labels: size/M

#138 Add heatmap data sending to frontend
  backend/internal/controller/server/msg_handler.go
  backend/internal/controller/server/msg_handler_test.go
  backend/internal/model/game.go
  backend/internal/model/game_test.go
Labels: size/M, Go

#140 Add all stats reset
  backend/internal/controller/server/msg_handler.go
  backend/internal/controller/server/server.go
  backend/internal/model/game.go
  backend/internal/model/game_test.go
Labels: size/S, Go
